[package]
name = "agent"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
dotenvy.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true

circuit-lang = { path = "../circuit-lang" }
kicad-bridge = { path = "../kicad-bridge" }
sch-engine = { path = "../sch-engine" }
indexmap.workspace = true
tempfile.workspace = true

[dev-dependencies]
tokio.workspace = true
