[package]
name = "pcb-place"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Concrete PCB placement algorithms."

[dependencies]
circuit-graph = { path = "../circuit-graph" }
geom = { path = "../geom" }
pcb-model = { path = "../pcb-model" }

[dev-dependencies]
pcb-drc = { path = "../pcb-drc" }
pcb-route-grid = { path = "../pcb-route-grid" }
serde_json.workspace = true
