[package]
name = "sch-engine"
version.workspace = true
edition.workspace = true

[dependencies]
circuit-lang = { path = "../circuit-lang" }
kicad-bridge = { path = "../kicad-bridge" }
kiutils_kicad.workspace = true
tempfile.workspace = true
uuid.workspace = true
indexmap.workspace = true

[dev-dependencies]
kiutils_kicad.workspace = true
tempfile.workspace = true
