[package]
name = "sch-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true, features = ["preserve_order"] }
uuid.workspace = true
regex = "1"
bincode = { version = "2", features = ["serde"] }
directories.workspace = true
tempfile.workspace = true
rayon.workspace = true

