[package]
name = "kicad-bridge"
version.workspace = true
edition.workspace = true

[dependencies]
circuit-lang = { path = "../circuit-lang" }
strsim.workspace = true
elsa.workspace = true
serde.workspace = true
serde_json.workspace = true
kiutils_kicad.workspace = true
kiutils_sexpr.workspace = true
tempfile.workspace = true
quick-xml.workspace = true
